### PR TITLE
Make Regional-CaseGen a package for convenience & add more output for the user

### PR DESCRIPTION
**Pull request by manishvenu**
This draft PR is a quality of life change for regional_casegen adding some more printed output to the user, a couple lines to stop some irrelevant CESM warnings, and dropping an __init__.py file so it can be imported as a package when cloned. Would love to discuss any opinions on these changes. A list of the changes are as follows:

1. Add print statements to setup_cesm to more clearly state exactly what we change
2. Set OCN_GRID and ICE_GRID xmlchange to the ESMF grid file so CESM stops throwing certain missing file warnings
3. Add __init__.py so it can be imported like a package when cloned  (gotta replace the "-" in regional-casegen with "_").
4. Make it a class with functions inside for future development.

### CODE REVIEW

**Comment by manishvenu** [comment]
This also makes RegionalCaseGen a class and works with the CRR repo

**Comment by manishvenu** [comment]
@enrico-mi Hey Enrico, can I mark you as a reviewer for this? I just want to make sure you are informed of the change before I push to main

 Thie main (setup_cesm) is now in a class, 
so going from 

`setup_cesm(expt, CESM_path, project = "p93300612")`

to 

```
reg_cas_obj = crr.regional_casegen.cesm_tools.RegionalCaseGen() # Create the Class
reg_cas_obj.setup_cesm(expt, CESM_path, project = "p93300612") # Call it like normally
```

This change will hopefully make it easier for more development in the future. If this change is okay with you, I'll merge it. There's a bunch of other small changes that don't matter too much.

**Comment by manishvenu** [comment]
Hey @ashjbarnes, I'd love to add you as a reviewer if you want! If not, I'll check with Enrico and merge when he's ready. There's not big changes to RCG other than making it a class....

**Review by enrico-mi — APPROVED** [review]

**Comment by enrico-mi** [comment]
Thanks for pinging me on this @manishvenu , it seems all good to me

**Comment by manishvenu** [comment]
> Thanks for pinging me on this @manishvenu , it seems all good to me

Thanks! I'll do some final debugging and merge back to main hopefully in an few hours.

**Comment by manishvenu** [comment]
I'll wait on merging this until I make sure the three boundary works (i.e. talk with Gio)

**Review by ashjbarnes — APPROVED** [review]
looks good!

**Comment by manishvenu** [comment]
Looks like three-boundary w/o tides is working and won't impact this... so I'll merge!

**Pull request merged**
